services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - 8085:80
    restart: always
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URL=mongodb://mongodb:27017/meteo_velo
      - PORT=3001
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - STRAVA_CALLBACK_URL=${STRAVA_CALLBACK_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - STACK_DIR=/app/stack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/appdata/dockge/stacks/meteo-velo:/app/stack
    restart: always
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017 # Permet à ton PC (VS Code) de se connecter au serveur
    volumes:
      - mongo_data:/data/db
    restart: always
volumes:
  mongo_data: null
