export const MDI_ICONS = [
  // --- SPORTS & LOISIRS ---
  { name: 'mdi-bike', category: 'Sports & Loisirs', tags: ['vélo', 'bicyclette', 'cyclisme', 'cycling', 'bike', 'road', 'route', 'vtt', 'gravel'] },
  { name: 'mdi-speedometer', category: 'Sports & Loisirs', tags: ['vitesse', 'rapide', 'fast', 'speed', 'course', 'compteur', 'performance'] },
  { name: 'mdi-run', category: 'Sports & Loisirs', tags: ['course', 'courir', 'running', 'jogging', 'footing', 'run', 'sport'] },
  { name: 'mdi-flash', category: 'Sports & Loisirs', tags: ['énergie', 'rapide', 'fast', 'speed', 'sprint', 'éclair', 'power'] },
  { name: 'mdi-walk', category: 'Sports & Loisirs', tags: ['marche', 'marcher', 'walking', 'piéton', 'pedestrian', 'balade', 'promenade'] },
  { name: 'mdi-hiking', category: 'Sports & Loisirs', tags: ['randonnée', 'hiking', 'trekking', 'montagne', 'marche', 'mountain', 'backpack'] },
  { name: 'mdi-swim', category: 'Sports & Loisirs', tags: ['natation', 'nager', 'swimming', 'piscine', 'pool', 'mer', 'eau', 'water'] },
  { name: 'mdi-sail-boat', category: 'Sports & Loisirs', tags: ['voile', 'bateau', 'sailing', 'boat', 'mer', 'vent', 'wind', 'sailboat', 'sail-boat'] },
  { name: 'mdi-rowing', category: 'Sports & Loisirs', tags: ['aviron', 'rowing', 'bateau', 'kayak', 'sport'] },
  { name: 'mdi-kayaking', category: 'Sports & Loisirs', tags: ['kayak', 'canoe', 'kayaking', 'eau', 'water'] },
  { name: 'mdi-ski', category: 'Sports & Loisirs', tags: ['ski', 'skiing', 'neige', 'snow', 'glisse', 'hiver', 'winter'] },
  { name: 'mdi-snowboard', category: 'Sports & Loisirs', tags: ['snowboard', 'snowboarding', 'neige', 'snow', 'glisse', 'hiver', 'winter'] },
  { name: 'mdi-skateboard', category: 'Sports & Loisirs', tags: ['skate', 'skateboard', 'roller', 'patins', 'glisse'] },
  { name: 'mdi-image-filter-hdr', category: 'Sports & Loisirs', tags: ['escalade', 'climbing', 'montagne', 'roc', 'rock', 'sommet', 'peak', 'altitude', 'alpes'] },
  { name: 'mdi-golf', category: 'Sports & Loisirs', tags: ['golf', 'sport', 'green'] },
  { name: 'mdi-tennis', category: 'Sports & Loisirs', tags: ['tennis', 'raquette', 'sport'] },
  { name: 'mdi-table-tennis', category: 'Sports & Loisirs', tags: ['ping pong', 'table tennis', 'raquette', 'sport'] },
  { name: 'mdi-badminton', category: 'Sports & Loisirs', tags: ['badminton', 'volant', 'raquette', 'sport'] },
  { name: 'mdi-soccer', category: 'Sports & Loisirs', tags: ['football', 'foot', 'soccer', 'ballon', 'ball'] },
  { name: 'mdi-basketball', category: 'Sports & Loisirs', tags: ['basketball', 'basket', 'ballon', 'ball'] },
  { name: 'mdi-volleyball', category: 'Sports & Loisirs', tags: ['volleyball', 'volley', 'ballon', 'ball'] },
  { name: 'mdi-rugby', category: 'Sports & Loisirs', tags: ['rugby', 'ballon', 'ball'] },
  { name: 'mdi-dumbbell', category: 'Sports & Loisirs', tags: ['musculation', 'fitness', 'gym', 'muscu', 'weight', 'dumbbell'] },
  { name: 'mdi-yoga', category: 'Sports & Loisirs', tags: ['yoga', 'étirement', 'stretching', 'bien-être', 'meditation'] },
  { name: 'mdi-spa', category: 'Sports & Loisirs', tags: ['méditation', 'zen', 'relaxation', 'yoga', 'spa', 'bien-être'] },
  { name: 'mdi-karate', category: 'Sports & Loisirs', tags: ['combat', 'arts martiaux', 'karate', 'judo', 'boxe', 'mixed-martial-arts'] },
  { name: 'mdi-bow-arrow', category: 'Sports & Loisirs', tags: ['tir à l\'arc', 'archery', 'flèche', 'arrow', 'arc', 'bow'] },
  { name: 'mdi-fish', category: 'Sports & Loisirs', tags: ['pêche', 'fishing', 'poisson', 'fish', 'eau', 'water'] },
  { name: 'mdi-horse', category: 'Sports & Loisirs', tags: ['équitation', 'cheval', 'horse', 'riding'] },

  // --- MÉTÉO & NATURE ---
  { name: 'mdi-weather-sunny', category: 'Météo & Nature', tags: ['soleil', 'sunny', 'sun', 'chaleur', 'beau temps'] },
  { name: 'mdi-weather-cloudy', category: 'Météo & Nature', tags: ['nuage', 'cloudy', 'cloud', 'couvert'] },
  { name: 'mdi-weather-windy', category: 'Météo & Nature', tags: ['vent', 'windy', 'wind', 'souffle', 'air'] },
  { name: 'mdi-weather-snowy', category: 'Météo & Nature', tags: ['neige', 'snowy', 'snow', 'froid', 'glace'] },
  { name: 'mdi-weather-pouring', category: 'Météo & Nature', tags: ['forte pluie', 'pouring', 'rain', 'orage'] },
  { name: 'mdi-weather-lightning', category: 'Météo & Nature', tags: ['orage', 'lightning', 'tempête', 'storm'] },
  { name: 'mdi-umbrella', category: 'Météo & Nature', tags: ['pluie', 'parapluie', 'rain', 'umbrella', 'protection'] },
  { name: 'mdi-leaf', category: 'Météo & Nature', tags: ['nature', 'feuille', 'leaf', 'écologie'] },
  { name: 'mdi-forest', category: 'Météo & Nature', tags: ['forêt', 'bois', 'forest', 'arbres', 'trees', 'nature'] },
  { name: 'mdi-water', category: 'Météo & Nature', tags: ['eau', 'water', 'pluie', 'rain', 'hydratation'] },

  // --- TRANSPORTS ---
  { name: 'mdi-motorbike', category: 'Transports', tags: ['moto', 'motorcycle', 'motorbike', 'scooter', 'deux roues', 'biker'] },
  { name: 'mdi-car', category: 'Transports', tags: ['voiture', 'auto', 'car', 'conduite', 'drive'] },
  { name: 'mdi-scooter', category: 'Transports', tags: ['trottinette', 'scooter', 'kick scooter'] },
  { name: 'mdi-moped', category: 'Transports', tags: ['cyclo', 'moped', 'scooter', 'vespa'] },
  { name: 'mdi-train', category: 'Transports', tags: ['train', 'sncf', 'rails', 'gare'] },
  { name: 'mdi-bus', category: 'Transports', tags: ['bus', 'autobus', 'transport'] },
  { name: 'mdi-subway', category: 'Transports', tags: ['métro', 'subway', 'underground', 'transport'] },
  { name: 'mdi-airplane', category: 'Transports', tags: ['avion', 'plane', 'flight', 'voyage', 'travel'] },

  // --- VIE QUOTIDIENNE & DIVERS ---
  { name: 'mdi-home', category: 'Quotidien & Divers', tags: ['maison', 'home', 'intérieur', 'indoor'] },
  { name: 'mdi-office-building', category: 'Quotidien & Divers', tags: ['bureau', 'travail', 'work', 'office', 'building'] },
  { name: 'mdi-store', category: 'Quotidien & Divers', tags: ['courses', 'magasin', 'shopping', 'store', 'market'] },
  { name: 'mdi-school', category: 'Quotidien & Divers', tags: ['école', 'school', 'études', 'universite'] },
  { name: 'mdi-heart-pulse', category: 'Quotidien & Divers', tags: ['cardio', 'santé', 'heart', 'pulse', 'vitality'] },
  { name: 'mdi-camera', category: 'Quotidien & Divers', tags: ['photo', 'appareil', 'camera', 'photography'] },
  { name: 'mdi-headphones', category: 'Quotidien & Divers', tags: ['musique', 'écouteurs', 'headphones', 'music', 'audio'] },
  { name: 'mdi-compass', category: 'Quotidien & Divers', tags: ['boussole', 'orientation', 'compass', 'nord', 'gps'] },
  { name: 'mdi-map-marker', category: 'Quotidien & Divers', tags: ['lieu', 'adresse', 'marker', 'gps', 'carte', 'map'] },
  { name: 'mdi-calendar', category: 'Quotidien & Divers', tags: ['calendrier', 'date', 'planning', 'agenda'] },
  { name: 'mdi-clock', category: 'Quotidien & Divers', tags: ['heure', 'temps', 'clock', 'time', 'durée'] },
  { name: 'mdi-shield-check', category: 'Quotidien & Divers', tags: ['sécurité', 'protection', 'shield', 'ok'] },
  { name: 'mdi-trophy', category: 'Quotidien & Divers', tags: ['compétition', 'trophée', 'victoire', 'trophy', 'cup', 'winner'] },
  { name: 'mdi-shoe-print', category: 'Quotidien & Divers', tags: ['chaussure', 'pas', 'steps', 'running', 'walking'] },
  { name: 'mdi-wheelchair', category: 'Quotidien & Divers', tags: ['fauteuil', 'pmr', 'wheelchair', 'accessibilité'] },
  { name: 'mdi-heart', category: 'Quotidien & Divers', tags: ['coeur', 'favori', 'love', 'heart'] },
  { name: 'mdi-star', category: 'Quotidien & Divers', tags: ['étoile', 'favori', 'star', 'rating'] },
  { name: 'mdi-lightbulb', category: 'Quotidien & Divers', tags: ['idée', 'ampoule', 'lightbulb', 'astuce'] },
  { name: 'mdi-book-open-variant', category: 'Quotidien & Divers', tags: ['lecture', 'livre', 'book', 'apprentissage'] },
  { name: 'mdi-music', category: 'Quotidien & Divers', tags: ['musique', 'music', 'note', 'chanson'] },
  { name: 'mdi-food-apple', category: 'Quotidien & Divers', tags: ['nutrition', 'pomme', 'apple', 'food', 'manger'] },
  { name: 'mdi-coffee', category: 'Quotidien & Divers', tags: ['café', 'pause', 'coffee', 'cup', 'mug'] },
  { name: 'mdi-beer', category: 'Quotidien & Divers', tags: ['bière', 'beer', 'afterwork', 'détente'] },
  { name: 'mdi-glass-wine', category: 'Quotidien & Divers', tags: ['vin', 'wine', 'verre', 'apéro'] },
  { name: 'mdi-grill', category: 'Quotidien & Divers', tags: ['barbecue', 'grill', 'bbq', 'cuisine', 'cooking', 'viande', 'grillade', 'repas', 'été', 'summer'] },
  { name: 'mdi-umbrella-beach', category: 'Quotidien & Divers', tags: ['plage', 'beach', 'parasol', 'sable', 'mer', 'vacances', 'baignade', 'soleil', 'détente', 'transat', 'bronzer', 'summer', 'été'] }
]
